name: Daily GitHub Contribution
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  make-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this to ensure the workflow can push changes
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run daily script
        run: python daily_script.py
      - name: Push changes
        run: |
          git config user.name "vrohlfs"
          git config user.email "51542009+vrohlfs@users.noreply.github.com"
          git add daily_files/
          git commit -m "Daily log file" || echo "No changes to commit"
          git push
